### ISSUE TITLE
Any chance to integrate with haxe?

### ISSUE THREAD

**Issue by hopewise** [nateware/fast-aes#6]
Hello,

I've used your library with a library called ASCrypt ( https://github.com/Meychi/ASCrypt )
Can you please check this issue here:

https://github.com/Meychi/ASCrypt/issues/4

Thanks,

**Comment by nateware** [comment]
The fast-aes gem is insecure and no longer recommended.  Please switch over to [Ruby OpenSSL](http://ruby-doc.org/stdlib-2.0/libdoc/openssl/rdoc/OpenSSL.html).
